<?php
/**
 * SubmissionDataRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  DocSpring
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DocSpring API
 *
 * Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-DOCSPRING
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DocSpring\Model;

use \ArrayAccess;
use \DocSpring\ObjectSerializer;

/**
 * SubmissionDataRequest Class Doc Comment
 *
 * @category Class
 * @package  DocSpring
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SubmissionDataRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'submission_data_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'email' => 'string',
        'name' => 'string',
        'order' => 'int',
        'sort_order' => 'int',
        'fields' => 'string[]',
        'metadata' => 'object',
        'state' => 'string',
        'viewed_at' => 'string',
        'completed_at' => 'string',
        'data' => 'object',
        'auth_type' => 'string',
        'auth_second_factor_type' => 'string',
        'auth_provider' => 'string',
        'auth_session_started_at' => 'string',
        'auth_session_id_hash' => 'string',
        'auth_user_id_hash' => 'string',
        'auth_username_hash' => 'string',
        'auth_phone_number_hash' => 'string',
        'ip_address' => 'string',
        'user_agent' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'email' => null,
        'name' => null,
        'order' => null,
        'sort_order' => null,
        'fields' => null,
        'metadata' => null,
        'state' => null,
        'viewed_at' => null,
        'completed_at' => null,
        'data' => null,
        'auth_type' => null,
        'auth_second_factor_type' => null,
        'auth_provider' => null,
        'auth_session_started_at' => null,
        'auth_session_id_hash' => null,
        'auth_user_id_hash' => null,
        'auth_username_hash' => null,
        'auth_phone_number_hash' => null,
        'ip_address' => null,
        'user_agent' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => true,
        'email' => true,
        'name' => true,
        'order' => true,
        'sort_order' => false,
        'fields' => true,
        'metadata' => true,
        'state' => false,
        'viewed_at' => true,
        'completed_at' => true,
        'data' => true,
        'auth_type' => false,
        'auth_second_factor_type' => false,
        'auth_provider' => true,
        'auth_session_started_at' => true,
        'auth_session_id_hash' => true,
        'auth_user_id_hash' => true,
        'auth_username_hash' => true,
        'auth_phone_number_hash' => true,
        'ip_address' => true,
        'user_agent' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'email' => 'email',
        'name' => 'name',
        'order' => 'order',
        'sort_order' => 'sort_order',
        'fields' => 'fields',
        'metadata' => 'metadata',
        'state' => 'state',
        'viewed_at' => 'viewed_at',
        'completed_at' => 'completed_at',
        'data' => 'data',
        'auth_type' => 'auth_type',
        'auth_second_factor_type' => 'auth_second_factor_type',
        'auth_provider' => 'auth_provider',
        'auth_session_started_at' => 'auth_session_started_at',
        'auth_session_id_hash' => 'auth_session_id_hash',
        'auth_user_id_hash' => 'auth_user_id_hash',
        'auth_username_hash' => 'auth_username_hash',
        'auth_phone_number_hash' => 'auth_phone_number_hash',
        'ip_address' => 'ip_address',
        'user_agent' => 'user_agent'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'email' => 'setEmail',
        'name' => 'setName',
        'order' => 'setOrder',
        'sort_order' => 'setSortOrder',
        'fields' => 'setFields',
        'metadata' => 'setMetadata',
        'state' => 'setState',
        'viewed_at' => 'setViewedAt',
        'completed_at' => 'setCompletedAt',
        'data' => 'setData',
        'auth_type' => 'setAuthType',
        'auth_second_factor_type' => 'setAuthSecondFactorType',
        'auth_provider' => 'setAuthProvider',
        'auth_session_started_at' => 'setAuthSessionStartedAt',
        'auth_session_id_hash' => 'setAuthSessionIdHash',
        'auth_user_id_hash' => 'setAuthUserIdHash',
        'auth_username_hash' => 'setAuthUsernameHash',
        'auth_phone_number_hash' => 'setAuthPhoneNumberHash',
        'ip_address' => 'setIpAddress',
        'user_agent' => 'setUserAgent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'email' => 'getEmail',
        'name' => 'getName',
        'order' => 'getOrder',
        'sort_order' => 'getSortOrder',
        'fields' => 'getFields',
        'metadata' => 'getMetadata',
        'state' => 'getState',
        'viewed_at' => 'getViewedAt',
        'completed_at' => 'getCompletedAt',
        'data' => 'getData',
        'auth_type' => 'getAuthType',
        'auth_second_factor_type' => 'getAuthSecondFactorType',
        'auth_provider' => 'getAuthProvider',
        'auth_session_started_at' => 'getAuthSessionStartedAt',
        'auth_session_id_hash' => 'getAuthSessionIdHash',
        'auth_user_id_hash' => 'getAuthUserIdHash',
        'auth_username_hash' => 'getAuthUsernameHash',
        'auth_phone_number_hash' => 'getAuthPhoneNumberHash',
        'ip_address' => 'getIpAddress',
        'user_agent' => 'getUserAgent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATE_PENDING = 'pending';
    public const STATE_COMPLETED = 'completed';
    public const AUTH_TYPE_NONE = 'none';
    public const AUTH_TYPE_PASSWORD = 'password';
    public const AUTH_TYPE_OAUTH = 'oauth';
    public const AUTH_TYPE_EMAIL_LINK = 'email_link';
    public const AUTH_TYPE_PHONE_NUMBER = 'phone_number';
    public const AUTH_TYPE_LDAP = 'ldap';
    public const AUTH_TYPE_SAML = 'saml';
    public const AUTH_SECOND_FACTOR_TYPE_NONE = 'none';
    public const AUTH_SECOND_FACTOR_TYPE_PHONE_NUMBER = 'phone_number';
    public const AUTH_SECOND_FACTOR_TYPE_TOTP = 'totp';
    public const AUTH_SECOND_FACTOR_TYPE_MOBILE_PUSH = 'mobile_push';
    public const AUTH_SECOND_FACTOR_TYPE_SECURITY_KEY = 'security_key';
    public const AUTH_SECOND_FACTOR_TYPE_FINGERPRINT = 'fingerprint';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStateAllowableValues()
    {
        return [
            self::STATE_PENDING,
            self::STATE_COMPLETED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAuthTypeAllowableValues()
    {
        return [
            self::AUTH_TYPE_NONE,
            self::AUTH_TYPE_PASSWORD,
            self::AUTH_TYPE_OAUTH,
            self::AUTH_TYPE_EMAIL_LINK,
            self::AUTH_TYPE_PHONE_NUMBER,
            self::AUTH_TYPE_LDAP,
            self::AUTH_TYPE_SAML,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAuthSecondFactorTypeAllowableValues()
    {
        return [
            self::AUTH_SECOND_FACTOR_TYPE_NONE,
            self::AUTH_SECOND_FACTOR_TYPE_PHONE_NUMBER,
            self::AUTH_SECOND_FACTOR_TYPE_TOTP,
            self::AUTH_SECOND_FACTOR_TYPE_MOBILE_PUSH,
            self::AUTH_SECOND_FACTOR_TYPE_SECURITY_KEY,
            self::AUTH_SECOND_FACTOR_TYPE_FINGERPRINT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('order', $data ?? [], null);
        $this->setIfExists('sort_order', $data ?? [], null);
        $this->setIfExists('fields', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('viewed_at', $data ?? [], null);
        $this->setIfExists('completed_at', $data ?? [], null);
        $this->setIfExists('data', $data ?? [], null);
        $this->setIfExists('auth_type', $data ?? [], null);
        $this->setIfExists('auth_second_factor_type', $data ?? [], null);
        $this->setIfExists('auth_provider', $data ?? [], null);
        $this->setIfExists('auth_session_started_at', $data ?? [], null);
        $this->setIfExists('auth_session_id_hash', $data ?? [], null);
        $this->setIfExists('auth_user_id_hash', $data ?? [], null);
        $this->setIfExists('auth_username_hash', $data ?? [], null);
        $this->setIfExists('auth_phone_number_hash', $data ?? [], null);
        $this->setIfExists('ip_address', $data ?? [], null);
        $this->setIfExists('user_agent', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['order'] === null) {
            $invalidProperties[] = "'order' can't be null";
        }
        if ($this->container['sort_order'] === null) {
            $invalidProperties[] = "'sort_order' can't be null";
        }
        if ($this->container['fields'] === null) {
            $invalidProperties[] = "'fields' can't be null";
        }
        if ($this->container['metadata'] === null) {
            $invalidProperties[] = "'metadata' can't be null";
        }
        if ($this->container['state'] === null) {
            $invalidProperties[] = "'state' can't be null";
        }
        $allowedValues = $this->getStateAllowableValues();
        if (!is_null($this->container['state']) && !in_array($this->container['state'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'state', must be one of '%s'",
                $this->container['state'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['viewed_at'] === null) {
            $invalidProperties[] = "'viewed_at' can't be null";
        }
        if ($this->container['completed_at'] === null) {
            $invalidProperties[] = "'completed_at' can't be null";
        }
        if ($this->container['data'] === null) {
            $invalidProperties[] = "'data' can't be null";
        }
        if ($this->container['auth_type'] === null) {
            $invalidProperties[] = "'auth_type' can't be null";
        }
        $allowedValues = $this->getAuthTypeAllowableValues();
        if (!is_null($this->container['auth_type']) && !in_array($this->container['auth_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'auth_type', must be one of '%s'",
                $this->container['auth_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['auth_second_factor_type'] === null) {
            $invalidProperties[] = "'auth_second_factor_type' can't be null";
        }
        $allowedValues = $this->getAuthSecondFactorTypeAllowableValues();
        if (!is_null($this->container['auth_second_factor_type']) && !in_array($this->container['auth_second_factor_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'auth_second_factor_type', must be one of '%s'",
                $this->container['auth_second_factor_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['auth_provider'] === null) {
            $invalidProperties[] = "'auth_provider' can't be null";
        }
        if ($this->container['auth_session_started_at'] === null) {
            $invalidProperties[] = "'auth_session_started_at' can't be null";
        }
        if ($this->container['auth_session_id_hash'] === null) {
            $invalidProperties[] = "'auth_session_id_hash' can't be null";
        }
        if ($this->container['auth_user_id_hash'] === null) {
            $invalidProperties[] = "'auth_user_id_hash' can't be null";
        }
        if ($this->container['auth_username_hash'] === null) {
            $invalidProperties[] = "'auth_username_hash' can't be null";
        }
        if ($this->container['auth_phone_number_hash'] === null) {
            $invalidProperties[] = "'auth_phone_number_hash' can't be null";
        }
        if ($this->container['ip_address'] === null) {
            $invalidProperties[] = "'ip_address' can't be null";
        }
        if ($this->container['user_agent'] === null) {
            $invalidProperties[] = "'user_agent' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            array_push($this->openAPINullablesSetToNull, 'email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets order
     *
     * @return int
     */
    public function getOrder()
    {
        return $this->container['order'];
    }

    /**
     * Sets order
     *
     * @param int $order order
     *
     * @return self
     */
    public function setOrder($order)
    {
        if (is_null($order)) {
            array_push($this->openAPINullablesSetToNull, 'order');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('order', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['order'] = $order;

        return $this;
    }

    /**
     * Gets sort_order
     *
     * @return int
     */
    public function getSortOrder()
    {
        return $this->container['sort_order'];
    }

    /**
     * Sets sort_order
     *
     * @param int $sort_order sort_order
     *
     * @return self
     */
    public function setSortOrder($sort_order)
    {
        if (is_null($sort_order)) {
            throw new \InvalidArgumentException('non-nullable sort_order cannot be null');
        }
        $this->container['sort_order'] = $sort_order;

        return $this;
    }

    /**
     * Gets fields
     *
     * @return string[]
     */
    public function getFields()
    {
        return $this->container['fields'];
    }

    /**
     * Sets fields
     *
     * @param string[] $fields fields
     *
     * @return self
     */
    public function setFields($fields)
    {
        if (is_null($fields)) {
            array_push($this->openAPINullablesSetToNull, 'fields');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fields', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fields'] = $fields;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return object
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param object $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            array_push($this->openAPINullablesSetToNull, 'metadata');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('metadata', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string $state state
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            throw new \InvalidArgumentException('non-nullable state cannot be null');
        }
        $allowedValues = $this->getStateAllowableValues();
        if (!in_array($state, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'state', must be one of '%s'",
                    $state,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets viewed_at
     *
     * @return string
     */
    public function getViewedAt()
    {
        return $this->container['viewed_at'];
    }

    /**
     * Sets viewed_at
     *
     * @param string $viewed_at viewed_at
     *
     * @return self
     */
    public function setViewedAt($viewed_at)
    {
        if (is_null($viewed_at)) {
            array_push($this->openAPINullablesSetToNull, 'viewed_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('viewed_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['viewed_at'] = $viewed_at;

        return $this;
    }

    /**
     * Gets completed_at
     *
     * @return string
     */
    public function getCompletedAt()
    {
        return $this->container['completed_at'];
    }

    /**
     * Sets completed_at
     *
     * @param string $completed_at completed_at
     *
     * @return self
     */
    public function setCompletedAt($completed_at)
    {
        if (is_null($completed_at)) {
            array_push($this->openAPINullablesSetToNull, 'completed_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('completed_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['completed_at'] = $completed_at;

        return $this;
    }

    /**
     * Gets data
     *
     * @return object
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param object $data data
     *
     * @return self
     */
    public function setData($data)
    {
        if (is_null($data)) {
            array_push($this->openAPINullablesSetToNull, 'data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['data'] = $data;

        return $this;
    }

    /**
     * Gets auth_type
     *
     * @return string
     */
    public function getAuthType()
    {
        return $this->container['auth_type'];
    }

    /**
     * Sets auth_type
     *
     * @param string $auth_type auth_type
     *
     * @return self
     */
    public function setAuthType($auth_type)
    {
        if (is_null($auth_type)) {
            throw new \InvalidArgumentException('non-nullable auth_type cannot be null');
        }
        $allowedValues = $this->getAuthTypeAllowableValues();
        if (!in_array($auth_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'auth_type', must be one of '%s'",
                    $auth_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['auth_type'] = $auth_type;

        return $this;
    }

    /**
     * Gets auth_second_factor_type
     *
     * @return string
     */
    public function getAuthSecondFactorType()
    {
        return $this->container['auth_second_factor_type'];
    }

    /**
     * Sets auth_second_factor_type
     *
     * @param string $auth_second_factor_type auth_second_factor_type
     *
     * @return self
     */
    public function setAuthSecondFactorType($auth_second_factor_type)
    {
        if (is_null($auth_second_factor_type)) {
            throw new \InvalidArgumentException('non-nullable auth_second_factor_type cannot be null');
        }
        $allowedValues = $this->getAuthSecondFactorTypeAllowableValues();
        if (!in_array($auth_second_factor_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'auth_second_factor_type', must be one of '%s'",
                    $auth_second_factor_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['auth_second_factor_type'] = $auth_second_factor_type;

        return $this;
    }

    /**
     * Gets auth_provider
     *
     * @return string
     */
    public function getAuthProvider()
    {
        return $this->container['auth_provider'];
    }

    /**
     * Sets auth_provider
     *
     * @param string $auth_provider auth_provider
     *
     * @return self
     */
    public function setAuthProvider($auth_provider)
    {
        if (is_null($auth_provider)) {
            array_push($this->openAPINullablesSetToNull, 'auth_provider');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auth_provider', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auth_provider'] = $auth_provider;

        return $this;
    }

    /**
     * Gets auth_session_started_at
     *
     * @return string
     */
    public function getAuthSessionStartedAt()
    {
        return $this->container['auth_session_started_at'];
    }

    /**
     * Sets auth_session_started_at
     *
     * @param string $auth_session_started_at auth_session_started_at
     *
     * @return self
     */
    public function setAuthSessionStartedAt($auth_session_started_at)
    {
        if (is_null($auth_session_started_at)) {
            array_push($this->openAPINullablesSetToNull, 'auth_session_started_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auth_session_started_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auth_session_started_at'] = $auth_session_started_at;

        return $this;
    }

    /**
     * Gets auth_session_id_hash
     *
     * @return string
     */
    public function getAuthSessionIdHash()
    {
        return $this->container['auth_session_id_hash'];
    }

    /**
     * Sets auth_session_id_hash
     *
     * @param string $auth_session_id_hash auth_session_id_hash
     *
     * @return self
     */
    public function setAuthSessionIdHash($auth_session_id_hash)
    {
        if (is_null($auth_session_id_hash)) {
            array_push($this->openAPINullablesSetToNull, 'auth_session_id_hash');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auth_session_id_hash', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auth_session_id_hash'] = $auth_session_id_hash;

        return $this;
    }

    /**
     * Gets auth_user_id_hash
     *
     * @return string
     */
    public function getAuthUserIdHash()
    {
        return $this->container['auth_user_id_hash'];
    }

    /**
     * Sets auth_user_id_hash
     *
     * @param string $auth_user_id_hash auth_user_id_hash
     *
     * @return self
     */
    public function setAuthUserIdHash($auth_user_id_hash)
    {
        if (is_null($auth_user_id_hash)) {
            array_push($this->openAPINullablesSetToNull, 'auth_user_id_hash');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auth_user_id_hash', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auth_user_id_hash'] = $auth_user_id_hash;

        return $this;
    }

    /**
     * Gets auth_username_hash
     *
     * @return string
     */
    public function getAuthUsernameHash()
    {
        return $this->container['auth_username_hash'];
    }

    /**
     * Sets auth_username_hash
     *
     * @param string $auth_username_hash auth_username_hash
     *
     * @return self
     */
    public function setAuthUsernameHash($auth_username_hash)
    {
        if (is_null($auth_username_hash)) {
            array_push($this->openAPINullablesSetToNull, 'auth_username_hash');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auth_username_hash', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auth_username_hash'] = $auth_username_hash;

        return $this;
    }

    /**
     * Gets auth_phone_number_hash
     *
     * @return string
     */
    public function getAuthPhoneNumberHash()
    {
        return $this->container['auth_phone_number_hash'];
    }

    /**
     * Sets auth_phone_number_hash
     *
     * @param string $auth_phone_number_hash auth_phone_number_hash
     *
     * @return self
     */
    public function setAuthPhoneNumberHash($auth_phone_number_hash)
    {
        if (is_null($auth_phone_number_hash)) {
            array_push($this->openAPINullablesSetToNull, 'auth_phone_number_hash');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auth_phone_number_hash', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auth_phone_number_hash'] = $auth_phone_number_hash;

        return $this;
    }

    /**
     * Gets ip_address
     *
     * @return string
     */
    public function getIpAddress()
    {
        return $this->container['ip_address'];
    }

    /**
     * Sets ip_address
     *
     * @param string $ip_address ip_address
     *
     * @return self
     */
    public function setIpAddress($ip_address)
    {
        if (is_null($ip_address)) {
            array_push($this->openAPINullablesSetToNull, 'ip_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ip_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ip_address'] = $ip_address;

        return $this;
    }

    /**
     * Gets user_agent
     *
     * @return string
     */
    public function getUserAgent()
    {
        return $this->container['user_agent'];
    }

    /**
     * Sets user_agent
     *
     * @param string $user_agent user_agent
     *
     * @return self
     */
    public function setUserAgent($user_agent)
    {
        if (is_null($user_agent)) {
            array_push($this->openAPINullablesSetToNull, 'user_agent');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user_agent', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['user_agent'] = $user_agent;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


